replicaCount: 1

env:
  # Hostname for the UI ingress rule
  FLUXNOVA_UI_HOST: "demo.fluxnova.finos.org"
  FXN_REST_API_URL: "http://fluxnova-engine:8080/engine-rest"
  FXN_FORCE_HTTP: "true"
  HOST: "0.0.0.0"
  PORT: "4000"
  FXN_OTEL_ENABLED: "false"

ingress:
  path: /()(.*)

image:
  # Docker Hub image for the FluxNova Control Center UI
  name: finos/fluxnova-control-center
  tag: latest
  pullPolicy: Always

imagePullSecrets: []

nameOverride: ""
fullnameOverride: "fluxnova-ui"

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  # Port exposed by the Kubernetes Service (and referenced in ingress-tls.yaml)
  port: 4000
  containerPort: 4000

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

