replicaCount: 1
env:
  FLUXNOVA_HOST: "fluxnova.example.com"

# Database configuration.
database:
  # Set to true to enable injection of DB_* env vars
  enabled: true

  # One Kubernetes Secret containing DB_URL, DB_USERNAME, DB_PASSWORD
  # This Secret will be loaded into the container using envFrom.secretRef.
  envFromSecretName: "fluxnova-db"
  driver: "org.postgresql.Driver"

image:
  name: finos/fluxnova-springboot-demo
  tag: latest
  pullPolicy: Always

imagePullSecrets:
  - name: ghcr-secret

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8080

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
